### ISSUE TITLE
Terminal text stays red after help output

### ISSUE THREAD

**Issue by kasimon** [xorpaul/g10k#59] opened 2017-06-16 07:52 UTC
After calling g10k without a config file, the console text stays red:

<pre>
~/sw/go/bin$ ./g10k 
2017/06/16 09:51:35 Error: you need to specify at least a config file or use the Puppetfile mode
Example call: ./g10k -config test.yaml or ./g10k -puppetfile
kheymann@dodo:~/sw/go/bin$  # console text is now red
</pre>

**Comment by xorpaul** [comment] 2017-06-16 10:47
Are you using a recent release of g10k?

Because I can't reproduce your problem:
![g10k-red](https://user-images.githubusercontent.com/938061/27223689-dd9bf208-5291-11e7-8ca3-c569b42337d0.png)

Are you using bash?

**Comment by kasimon** [comment] 2017-06-16 11:14
Hi @xorpaul, 

you are using a colored bash prompt that changes the color by itself. You should be able to reproduce it when you set PS1 to something simple like '\u@\h:\w\$'.

![bildschirmfoto vom 2017-06-16 13-08-52](https://user-images.githubusercontent.com/78341/27224459-8a422c4a-5295-11e7-8abb-1cea3f5d7773.png)

See the red prompt after the g10k command. As soon as I run a command that uses color (like ls in my case) the color is reset.

**Comment by xorpaul** [comment] 2017-06-16 11:42
Ah, that makes sense.

Thanks for reporting this.

Fixed in https://github.com/xorpaul/g10k/releases/tag/v0.3.6
https://github.com/xorpaul/g10k/commit/66826c4b546814ea40633614f7818bb6e6028fb6

**Closed by xorpaul** 2017-06-16 11:42 UTC

**Comment by kasimon** [comment] 2017-06-16 12:17
Awesome, thanks!
