### ISSUE TITLE
Request/Question: Alternative go-native Puppetfile

### ISSUE THREAD

**Issue by mschuchard** [xorpaul/g10k#86] opened 2017-12-13 16:04 UTC
I see in other issues that there is an idea to use a different format for the Puppetfile which is more go-friendly since parsing Ruby in Go is kind of awkward. Is there any visibility into the progress or architecture information on this? I am especially wondering (for the architecture) if the file will still be named Puppetfile or if it will be named something different, since that affects control repo structure in different ways (or if something like a C preproc would be viable).

Side note: It would be great if you could present on this software for Puppet Conf 2018. That will really help internal adoption so this can be pitched to enterprise companies.

**Comment by maxadamo** [comment] 2017-12-14 08:30
Entirely agree the second part. 
If we speak for different configuration support, there is already yaml support if I'm not wrong.

**Comment by mschuchard** [comment] 2017-12-14 11:36
I do not see documentation for the "yaml" format Puppetfile. Do you have a link for it?

**Comment by maxadamo** [comment] 2017-12-14 12:50
Now I'm not seeing it too.... but since I'm using from the beginning I'm sure that it was there. 
And as I remember the Puppetfile was kept only for compatibility, but the people started asking to make the tool more and more compatible with r10k (to ease the move).
You could either grep in the cloned repository, or check git logs to understand if this support has been removed.

**Comment by mschuchard** [comment] 2017-12-14 13:10
This is all I see and it is using the Ruby Puppetfile: https://github.com/xorpaul/g10k/blob/master/config.go#L138

**Comment by maxadamo** [comment] 2017-12-14 13:42
There you go:
https://github.com/xorpaul/g10k/blob/master/test.yaml
and tghe command to use the yaml is: `-config test.yaml`

**Comment by mschuchard** [comment] 2017-12-14 15:12
That is a config file though, which is already yaml.

**Comment by xorpaul** [comment] 2017-12-14 15:29
Hi there,

there is currently no support for a Puppetfile in a different config format than the current one.

I only have a local development branch with some support for a Puppetfile in a YAML format.
My plan to introduce a different Puppetfile config format is to only use the new format if it exists in the control repository branch and otherwise use the old one.

So if g10k would find something like `Puppetfile.yaml` inside the control repository branch it would use that. I'm still not sure if g10k should then also look inside the normal `Puppetfile` and somehow merge the modules. I'm also thinking about supporting a `Puppetfile.d` directory with multiple Puppetfiles inside.

Regarding the second part, I'm really glad that some people find this project helpful, but I'm currently don't see any wide interest in this project and none from Puppetlabs. They are invested in their `r10k` project and that's totally understandable. There is also a patch for `r10k` flying around that enables parallel module population, but it was never merged, because they don't want one failing module leaving all Puppet environment in an incomplete and undetermined state. Even more so, because their `r10k` tutorial runs `r10k` directly on the Puppetservers and not on a sync system that only deploys the Puppet environments after an successful run, like `g10k` was intended for.

Also California is pretty far away from Germany 😉

**Comment by maxadamo** [comment] 2017-12-14 16:12
mmh... I never tried the functionality and I thought it was working. 
But you know, I never got their point? Puppet is a kind of tool, where everything is a single point of failure. A failure of foreman, or puppetdb will result in puppet being unusable (unless you reconfigure the server to not use them), and one should care about a temporary failure that could be recovered in less that a minute? 
See logs below: 4 seconds against 5 minutes, to sync 141 repositories:
`2017-12-14 11:56:18,878 INFO 62.40.106.228 - - [14/Dec/2017 11:56:18] "GET /g10k/repositories/test HTTP/1.1" 200 -`
`2017-12-14 11:56:40,303 INFO ======== Received trigger for branch: uat ========`
`2017-12-14 11:56:40,304 INFO ==== Start update of puppet env: uat`
`2017-12-14 11:56:40,479 INFO stashing changes on /etc/puppetlabs/code/environments/uat: No local changes to save`
`2017-12-14 11:56:40,518 INFO running g10k for environment uat`
`2017-12-14 11:56:44,857 INFO Synced ./Puppetfile with 93 git repositories and 48 Forge modules in 4.3s with git (3.9s sync, I/O 0.1s) and Forge (1.0s query+download, I/O 1.0s) using 70 resolv and 20 extract workers`
`2017-12-14 11:56:44,858 INFO ==== End update of puppet env: uat`
`2017-12-14 11:56:44,858 INFO ======== Trigger processed in 4 seconds ========`

**Comment by mschuchard** [comment] 2017-12-14 16:34
> Also California is pretty far away from Germany

There is one in Europe too. RIPieenar is going to that one since the U.S. had issues with him visiting from Malta. I really want this as a supported backend for Code Manager and I think that could make it happen.

Anyway, a Puppetfile.yaml would be a great direction I think. Also if there was a REST API for remote calls from e.g. Jenkins server doing Puppet CI/CD.

**Closed** 2017-12-14 16:35 UTC
